var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
import { PALETTE } from "../../tokens/color";
import { FONT_WEIGHT } from "../../tokens/font";
export var StyledSelectField = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: relative;\n\n  .button {\n    justify-content: space-between;\n    text-align: left !important;\n    width: 100%;\n    font-weight: ", ";\n    border: 1.5px solid ", " !important;\n    background: ", ";\n    border-radius: ", " !important;\n\n    .icon {\n      justify-self: flex-end;\n      margin-left: 25px;\n      transform: ", ";\n      transition: all ease-in-out 0.2s;\n    }\n  }\n"], ["\n  position: relative;\n\n  .button {\n    justify-content: space-between;\n    text-align: left !important;\n    width: 100%;\n    font-weight: ", ";\n    border: 1.5px solid ", " !important;\n    background: ", ";\n    border-radius: ", " !important;\n\n    .icon {\n      justify-self: flex-end;\n      margin-left: 25px;\n      transform: ", ";\n      transition: all ease-in-out 0.2s;\n    }\n  }\n"])), FONT_WEIGHT.w400, PALETTE.ash, function (props) { return PALETTE[props.background]; }, function (props) { return props.borderRadius; }, function (props) {
    return props.focused ? "rotateZ(180deg)" : "rotateZ(0deg)";
});
export var StyledOptionsContainer = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  position: absolute;\n  width: 100%;\n  left: 0px;\n  top: 60px;\n  z-index: 99;\n  visibility: ", ";\n  pointer-events: ", ";\n  box-shadow: 0 0 7px 2px ", ";\n  background: ", ";\n  padding: 10px 0;\n  height: ", ";\n  overflow-y: auto;\n\n  ::-webkit-scrollbar {\n    width: 7px;\n  }\n\n  ::-webkit-scrollbar-track {\n    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);\n    border-radius: 15px;\n  }\n\n  ::-webkit-scrollbar-thumb {\n    background-color: ", ";\n    border-radius: 15px;\n  }\n  &.up {\n    top: -140px;\n  }\n\n  &.down {\n    top: 70px;\n  }\n"], ["\n  position: absolute;\n  width: 100%;\n  left: 0px;\n  top: 60px;\n  z-index: 99;\n  visibility: ", ";\n  pointer-events: ", ";\n  box-shadow: 0 0 7px 2px ", ";\n  background: ", ";\n  padding: 10px 0;\n  height: ", ";\n  overflow-y: auto;\n\n  ::-webkit-scrollbar {\n    width: 7px;\n  }\n\n  ::-webkit-scrollbar-track {\n    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);\n    border-radius: 15px;\n  }\n\n  ::-webkit-scrollbar-thumb {\n    background-color: ", ";\n    border-radius: 15px;\n  }\n  &.up {\n    top: -140px;\n  }\n\n  &.down {\n    top: 70px;\n  }\n"])), function (props) { return (props.focused ? "visible" : "hidden"); }, function (props) { return (props.focused ? "auto" : "none"); }, PALETTE.grey, PALETTE.light, function (props) {
    return props.focused ? "".concat(props.height && props.height, "px") : "180px";
}, PALETTE.primary);
export var StyledOptions = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  background: ", ";\n  padding: 15px;\n  cursor: pointer;\n  transition: all ease-in-out 0.2s;\n  margin: 0 10px;\n  border-radius: 10px;\n\n  :hover {\n    background: ", ";\n    transition: all ease-in-out 0.2s;\n  }\n"], ["\n  background: ", ";\n  padding: 15px;\n  cursor: pointer;\n  transition: all ease-in-out 0.2s;\n  margin: 0 10px;\n  border-radius: 10px;\n\n  :hover {\n    background: ", ";\n    transition: all ease-in-out 0.2s;\n  }\n"])), function (props) {
    return props.selected ? "".concat(PALETTE.primary) : "".concat(PALETTE.light);
}, PALETTE.grey);
var templateObject_1, templateObject_2, templateObject_3;
//# sourceMappingURL=styled.js.map