var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
import { PALETTE } from "../../tokens/color";
import { FONT_SIZE } from "../../tokens/font";
import { HEIGHTS, mediaQueries, SIDE_PADDINGS } from "../../tokens/sizes";
export var StyledNavbar = styled.section(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  background-color: ", ";\n  padding: ", "px ", "px;\n  border-bottom: 1px solid ", ";\n  position: sticky;\n  top: 0;\n  z-index: 999;\n"], ["\n  background-color: ", ";\n  padding: ", "px ", "px;\n  border-bottom: 1px solid ", ";\n  position: sticky;\n  top: 0;\n  z-index: 999;\n"])), PALETTE.light, SIDE_PADDINGS.default, SIDE_PADDINGS.small, PALETTE.grey);
export var StyledGrid = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: grid;\n  align-items: center;\n  justify-content: space-between;\n  grid-template-columns: 1fr;\n  gap: 2rem;\n  & div:first-child,\n  & div:last-child {\n    display: none;\n  }\n  ", "\n"], ["\n  display: grid;\n  align-items: center;\n  justify-content: space-between;\n  grid-template-columns: 1fr;\n  gap: 2rem;\n  & div:first-child,\n  & div:last-child {\n    display: none;\n  }\n  ", "\n"])), mediaQueries("lg")("\n    grid-template-columns: 0.6fr auto;\n    & div:first-child, & div:last-child {\n        display:block;\n    }\n    "));
export var StyledMain = styled.main(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  .nav {\n    border-radius: 0px !important;\n    padding: 10px 0;\n    height: 100vh;\n    overflow-y: auto;\n  }\n"], ["\n  .nav {\n    border-radius: 0px !important;\n    padding: 10px 0;\n    height: 100vh;\n    overflow-y: auto;\n  }\n"])));
export var StyledSearchInput = styled.input(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  border-radius: 4px 0 0 4px;\n  height: ", "px;\n  padding: 0 20px;\n  width: 100%;\n  border: 2px solid ", ";\n  &:focus {\n    outline: 0;\n  }\n\n  &::placeholder {\n    color: ", ";\n    font-size: ", ";\n  }\n"], ["\n  border-radius: 4px 0 0 4px;\n  height: ", "px;\n  padding: 0 20px;\n  width: 100%;\n  border: 2px solid ", ";\n  &:focus {\n    outline: 0;\n  }\n\n  &::placeholder {\n    color: ", ";\n    font-size: ", ";\n  }\n"])), HEIGHTS.inputs.default, PALETTE.primary, PALETTE.ash, FONT_SIZE.pSmall);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=styled.js.map