var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
import { PALETTE } from "../../tokens/color";
import { FONT_SIZE } from "../../tokens/font";
import { HEIGHTS, mediaQueries, SIDE_PADDINGS, VIEWPORT, } from "../../tokens/sizes";
export var StyledNavbar = styled.section(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  background-color: ", ";\n  padding: ", "px ", "px;\n  border-bottom: 1px solid ", ";\n  position: sticky;\n  top: 0;\n  z-index: 999;\n"], ["\n  background-color: ", ";\n  padding: ", "px ", "px;\n  border-bottom: 1px solid ", ";\n  position: sticky;\n  top: 0;\n  z-index: 999;\n"])), PALETTE.light, SIDE_PADDINGS.default, SIDE_PADDINGS.small, PALETTE.grey);
export var StyledGrid = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  position: relative;\n  display: grid;\n  align-items: center;\n  justify-content: space-between;\n  grid-template-columns: 1fr;\n  gap: 2rem;\n  & div:first-child,\n  & div:last-child {\n    display: none;\n  }\n  ", "\n\n  .menu-icon {\n    display: none;\n    cursor: pointer;\n\n    @media (max-width: ", "px) {\n      display: initial;\n    }\n  }\n"], ["\n  position: relative;\n  display: grid;\n  align-items: center;\n  justify-content: space-between;\n  grid-template-columns: 1fr;\n  gap: 2rem;\n  & div:first-child,\n  & div:last-child {\n    display: none;\n  }\n  ", "\n\n  .menu-icon {\n    display: none;\n    cursor: pointer;\n\n    @media (max-width: ", "px) {\n      display: initial;\n    }\n  }\n"])), mediaQueries("lg")("\n    grid-template-columns: 0.6fr auto;\n    & div:first-child, & div:last-child {\n        display:block;\n    }\n    "), VIEWPORT.sm);
export var StyledMain = styled.main(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  position: relative;\n"], ["\n  position: relative;\n"])));
export var StyledSideNav = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  border-radius: 0px !important;\n  padding: 10px 0;\n  height: 100vh;\n  overflow-y: auto;\n  top: 0;\n  width: ", "px;\n  background: ", ";\n  position: sticky;\n\n  @media (max-width: ", "px) {\n    position: fixed;\n    top: 0;\n    overflow-x: hidden;\n    left: ", ";\n    transition: all ease-in-out 0.3s;\n    z-index: 9999;\n  }\n\n  @media (max-width: ", "px) {\n    position: fixed;\n    top: 0;\n    overflow-x: hidden;\n    left: ", ";\n    transition: all ease-in-out 0.3s;\n    z-index: 9999;\n  }\n"], ["\n  border-radius: 0px !important;\n  padding: 10px 0;\n  height: 100vh;\n  overflow-y: auto;\n  top: 0;\n  width: ", "px;\n  background: ", ";\n  position: sticky;\n\n  @media (max-width: ", "px) {\n    position: fixed;\n    top: 0;\n    overflow-x: hidden;\n    left: ", ";\n    transition: all ease-in-out 0.3s;\n    z-index: 9999;\n  }\n\n  @media (max-width: ", "px) {\n    position: fixed;\n    top: 0;\n    overflow-x: hidden;\n    left: ", ";\n    transition: all ease-in-out 0.3s;\n    z-index: 9999;\n  }\n"])), function (props) { return props.width; }, PALETTE.light, VIEWPORT.sm, function (props) { return (props.open ? "0%" : "-".concat(VIEWPORT.sm, "px")); }, VIEWPORT.md, function (props) { return (props.open ? "0%" : "-".concat(VIEWPORT.md, "px")); });
export var StyledSearchInput = styled.input(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  border-radius: 4px 0 0 4px;\n  height: ", "px;\n  padding: 0 20px;\n  width: 100%;\n  border: 2px solid ", ";\n  &:focus {\n    outline: 0;\n  }\n\n  &::placeholder {\n    color: ", ";\n    font-size: ", ";\n  }\n"], ["\n  border-radius: 4px 0 0 4px;\n  height: ", "px;\n  padding: 0 20px;\n  width: 100%;\n  border: 2px solid ", ";\n  &:focus {\n    outline: 0;\n  }\n\n  &::placeholder {\n    color: ", ";\n    font-size: ", ";\n  }\n"])), HEIGHTS.inputs.default, PALETTE.primary, PALETTE.ash, FONT_SIZE.pSmall);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
//# sourceMappingURL=styled.js.map