var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
import { PALETTE } from "../../tokens/color";
export var StyledCheckboxContainer = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n"], ["\n  display: flex;\n  align-items: center;\n"])));
export var StyledHiddenCheckbox = styled.input.attrs({ type: "checkbox" })(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  border: 0;\n  clip: rect(0 0 0 0);\n  clippath: inset(50%);\n  height: 0px;\n  margin: -1px;\n  overflow: hidden;\n  padding: 0;\n  position: relative;\n  white-space: nowrap;\n  width: 0px;\n"], ["\n  border: 0;\n  clip: rect(0 0 0 0);\n  clippath: inset(50%);\n  height: 0px;\n  margin: -1px;\n  overflow: hidden;\n  padding: 0;\n  position: relative;\n  white-space: nowrap;\n  width: 0px;\n"])));
export var StyledCheckboxLabel = styled.label(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  position: relative;\n  display: flex;\n  align-items: center;\n  cursor: pointer;\n\n  ::before {\n    cursor: pointer;\n    position: absolute;\n    left: 0px;\n    content: \" \";\n    width: 16px;\n    height: 16px;\n    border: 2px solid ", ";\n    border-radius: 5px;\n  }\n\n  ::after {\n    cursor: pointer;\n    position: absolute;\n    left: 2px;\n    content: \"\u2713\";\n    display: flex;\n    justify-content: center;\n    align-items: center;\n    width: 16px;\n    height: 16px;\n    border-radius: 2.5px;\n    background-color: ", ";\n  }\n"], ["\n  position: relative;\n  display: flex;\n  align-items: center;\n  cursor: pointer;\n\n  ::before {\n    cursor: pointer;\n    position: absolute;\n    left: 0px;\n    content: \" \";\n    width: 16px;\n    height: 16px;\n    border: 2px solid ", ";\n    border-radius: 5px;\n  }\n\n  ::after {\n    cursor: pointer;\n    position: absolute;\n    left: 2px;\n    content: \"\u2713\";\n    display: flex;\n    justify-content: center;\n    align-items: center;\n    width: 16px;\n    height: 16px;\n    border-radius: 2.5px;\n    background-color: ", ";\n  }\n"])), PALETTE.dark, PALETTE.primary);
export var StyledCheckboxText = styled.small(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  margin: 0 30px;\n"], ["\n  margin: 0 30px;\n"])));
export default StyledHiddenCheckbox;
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=styled.js.map