var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
import { PALETTE } from "../../tokens/color";
export var StyledPageNumber = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  padding: 10px 15px;\n  border: 1px solid ", ";\n  border-radius: 10px;\n  background: ", ";\n  cursor: pointer;\n"], ["\n  padding: 10px 15px;\n  border: 1px solid ", ";\n  border-radius: 10px;\n  background: ", ";\n  cursor: pointer;\n"])), PALETTE.primary, function (props) { return (props.selected ? PALETTE.primary : PALETTE.light); });
export var StyledPageButton = styled.button(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  padding: 7.5px 10px;\n  border: 1px solid ", ";\n  background: ", ";\n  border-radius: 10px;\n  outline: none;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  opacity: ", ";\n\n  svg {\n    vertical-align: middle;\n    path {\n      fill: ", ";\n    }\n  }\n\n  cursor: ", ";\n"], ["\n  padding: 7.5px 10px;\n  border: 1px solid ", ";\n  background: ", ";\n  border-radius: 10px;\n  outline: none;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  opacity: ", ";\n\n  svg {\n    vertical-align: middle;\n    path {\n      fill: ", ";\n    }\n  }\n\n  cursor: ", ";\n"])), PALETTE.primary, PALETTE.primary, function (props) { return (props.disabled ? "0.5" : "1"); }, function (props) { return (props.disabled ? PALETTE.ash : PALETTE.dark); }, function (props) { return (props.disabled ? "no-drop" : "pointer"); });
var templateObject_1, templateObject_2;
//# sourceMappingURL=styled.js.map