var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
import { PALETTE } from "../../tokens/color";
var StyledModal = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: fixed;\n  overflow: hidden;\n  top: 0;\n  left: 0;\n  background-color: rgba(0, 0, 0, 0.65);\n  width: 100%;\n  height: 100vh;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  padding: 1.5em 1em;\n  z-index: 999999;\n  box-sizing: border-box;\n  backdrop-filter: blur(8px);\n\n  .modal_fade_in {\n    opacity: 1;\n    transition: all 0.3s ease-in-out;\n    display: initial;\n  }\n  .modal_fade_out {\n    opacity: 0;\n    transition: all 0.3s ease-in-out;\n    display: none;\n  }\n"], ["\n  position: fixed;\n  overflow: hidden;\n  top: 0;\n  left: 0;\n  background-color: rgba(0, 0, 0, 0.65);\n  width: 100%;\n  height: 100vh;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  padding: 1.5em 1em;\n  z-index: 999999;\n  box-sizing: border-box;\n  backdrop-filter: blur(8px);\n\n  .modal_fade_in {\n    opacity: 1;\n    transition: all 0.3s ease-in-out;\n    display: initial;\n  }\n  .modal_fade_out {\n    opacity: 0;\n    transition: all 0.3s ease-in-out;\n    display: none;\n  }\n"])));
var StyledModalClose = styled.button(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  position: fixed;\n  top: 2.5%;\n  right: 1.5%;\n  background: transparent;\n  border: none !important;\n  padding: 10px;\n  cursor: pointer;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n\n  svg {\n    path {\n      fill: ", ";\n    }\n  }\n"], ["\n  position: fixed;\n  top: 2.5%;\n  right: 1.5%;\n  background: transparent;\n  border: none !important;\n  padding: 10px;\n  cursor: pointer;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n\n  svg {\n    path {\n      fill: ", ";\n    }\n  }\n"])), PALETTE.light);
var StyledModalBody = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  max-width: 95%;\n  width: ", "px;\n  height: auto;\n  overflow-x: hidden;\n  overflow-y: auto;\n"], ["\n  max-width: 95%;\n  width: ", "px;\n  height: auto;\n  overflow-x: hidden;\n  overflow-y: auto;\n"])), function (props) { return (props.width ? props.width : 450); });
export { StyledModal, StyledModalBody, StyledModalClose };
var templateObject_1, templateObject_2, templateObject_3;
//# sourceMappingURL=styles.js.map