var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
import { PALETTE } from "../../tokens/color";
import { FONT_WEIGHT } from "../../tokens/font";
export var StyledRangeContainer = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n  margin: 10px 0 30px 0;\n  position: relative;\n"], ["\n  display: flex;\n  align-items: center;\n  margin: 10px 0 30px 0;\n  position: relative;\n"])));
var StyledRange = styled.input.attrs({ type: "range" })(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  position: absolute;\n  top: 5px;\n  left: 5px;\n  width: 100%;\n  -webkit-appearance: none;\n  appearance: none;\n  background: transparent;\n  cursor: pointer;\n\n  ::-webkit-slider-runnable-track {\n    background: ", ";\n    height: 0.25rem;\n    border-radius: 5px;\n  }\n\n  ::-webkit-slider-thumb {\n    -webkit-appearance: none;\n    appearance: none;\n    margin-top: -6px;\n    background-color: ", ";\n    border-radius: 50%;\n    height: 1rem;\n    width: 1rem;\n    position: relative;\n    z-index: 25;\n  }\n\n  :focus::-webkit-slider-thumb {\n    border: 1px solid ", ";\n    outline: 2px solid ", ";\n    outline-offset: 0.125rem;\n  }\n"], ["\n  position: absolute;\n  top: 5px;\n  left: 5px;\n  width: 100%;\n  -webkit-appearance: none;\n  appearance: none;\n  background: transparent;\n  cursor: pointer;\n\n  ::-webkit-slider-runnable-track {\n    background: ", ";\n    height: 0.25rem;\n    border-radius: 5px;\n  }\n\n  ::-webkit-slider-thumb {\n    -webkit-appearance: none;\n    appearance: none;\n    margin-top: -6px;\n    background-color: ", ";\n    border-radius: 50%;\n    height: 1rem;\n    width: 1rem;\n    position: relative;\n    z-index: 25;\n  }\n\n  :focus::-webkit-slider-thumb {\n    border: 1px solid ", ";\n    outline: 2px solid ", ";\n    outline-offset: 0.125rem;\n  }\n"])), PALETTE.primary, PALETTE.primary, PALETTE.primary, PALETTE.primary);
export var StyledRangeDisplay = styled.input(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  padding: 10px;\n  width: 80px;\n  text-align: center;\n  font-weight: ", ";\n"], ["\n  padding: 10px;\n  width: 80px;\n  text-align: center;\n  font-weight: ", ";\n"])), FONT_WEIGHT.w600);
export default StyledRange;
var templateObject_1, templateObject_2, templateObject_3;
//# sourceMappingURL=styled.js.map