var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
import { PALETTE } from "../../tokens/color";
import { FONT_WEIGHT } from "../../tokens/font";
export var StyledRadioContainer = styled.label(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  align-items: ", ";\n  width: ", ";\n  border: ", ";\n  padding: ", ";\n  border-radius: ", ";\n  cursor: pointer;\n  position: relative;\n"], ["\n  display: flex;\n  align-items: ", ";\n  width: ", ";\n  border: ", ";\n  padding: ", ";\n  border-radius: ", ";\n  cursor: pointer;\n  position: relative;\n"])), function (props) { return (props.fullWidth ? "flex-start" : "center"); }, function (props) { return (props.fullWidth ? "100%" : "fit-content"); }, function (props) {
    return props.fullWidth ? "1.5px solid ".concat(PALETTE.border) : "none";
}, function (props) { return (props.fullWidth ? "20px" : "0px"); }, function (props) { return props.fullWidth && "5px"; });
export var StyledRadioText = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  width: ", ";\n  display: flex;\n  flex-direction: column;\n  margin: 0 5px;\n  font-weight: ", ";\n"], ["\n  width: ", ";\n  display: flex;\n  flex-direction: column;\n  margin: 0 5px;\n  font-weight: ", ";\n"])), function (props) { return (props.fullWidth ? "100%" : "fit-content"); }, function (props) {
    return props.fullWidth ? FONT_WEIGHT.w500 : FONT_WEIGHT.w400;
});
export var StyledColorRadio = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  width: 40px;\n  height: 40px;\n  background-color: ", ";\n  border-radius: 50%;\n"], ["\n  width: 40px;\n  height: 40px;\n  background-color: ", ";\n  border-radius: 50%;\n"])), function (props) { return props.hexColor; });
export var StyledSubLabel = styled.small(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  color: ", ";\n  margin-top: 5px;\n"], ["\n  color: ", ";\n  margin-top: 5px;\n"])), PALETTE.ash);
export var StyledRadio = styled.input(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  -webkit-appearance: none;\n  appearance: none;\n  background-color: ", ";\n  margin: 0 5px;\n  font: inherit;\n  color: ", ";\n  width: 1.15em;\n  height: 1.15em;\n  border: 2px solid ", ";\n  border-radius: 50%;\n  transform: translateY(-0.075em);\n  display: grid;\n  place-content: center;\n\n  &:checked {\n    border: 2px solid ", ";\n  }\n\n  ::before {\n    content: \"\";\n    width: 0.65em;\n    height: 0.65em;\n    transform: scale(0);\n    transition: 120ms transform ease-in-out;\n    box-shadow: inset 1em 1em ", ";\n    border-radius: 50%;\n  }\n\n  &:checked::before {\n    transform: scale(1);\n  }\n\n  margin: 0 5px;\n  display: ", ";\n\n  &:checked + ", " {\n    outline: 3px solid ", ";\n    outline-offset: 3px;\n  }\n"], ["\n  -webkit-appearance: none;\n  appearance: none;\n  background-color: ", ";\n  margin: 0 5px;\n  font: inherit;\n  color: ", ";\n  width: 1.15em;\n  height: 1.15em;\n  border: 2px solid ", ";\n  border-radius: 50%;\n  transform: translateY(-0.075em);\n  display: grid;\n  place-content: center;\n\n  &:checked {\n    border: 2px solid ", ";\n  }\n\n  ::before {\n    content: \"\";\n    width: 0.65em;\n    height: 0.65em;\n    transform: scale(0);\n    transition: 120ms transform ease-in-out;\n    box-shadow: inset 1em 1em ", ";\n    border-radius: 50%;\n  }\n\n  &:checked::before {\n    transform: scale(1);\n  }\n\n  margin: 0 5px;\n  display: ", ";\n\n  &:checked + ", " {\n    outline: 3px solid ", ";\n    outline-offset: 3px;\n  }\n"])), PALETTE.light, PALETTE.dark, PALETTE.dark, PALETTE.primary, PALETTE.primary, function (props) { return (props.forColor ? "none" : "block"); }, StyledColorRadio, PALETTE.primary);
export var StyledDismissable = styled.button(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  position: absolute;\n  top: -5px;\n  right: 5px;\n  padding: 0;\n  width: 20px;\n  height: 20px;\n  border: none;\n  outline: none;\n  border-radius: 50%;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  cursor: pointer;\n  background: ", ";\n\n  svg {\n    path {\n      fill: ", ";\n    }\n  }\n"], ["\n  position: absolute;\n  top: -5px;\n  right: 5px;\n  padding: 0;\n  width: 20px;\n  height: 20px;\n  border: none;\n  outline: none;\n  border-radius: 50%;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  cursor: pointer;\n  background: ", ";\n\n  svg {\n    path {\n      fill: ", ";\n    }\n  }\n"])), function (props) {
    return props.background ? PALETTE[props.background] : PALETTE["dark"];
}, function (props) {
    return props.background ? PALETTE[props.background] : PALETTE["light"];
});
export default StyledRadio;
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
//# sourceMappingURL=styled.js.map