var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
import { PALETTE } from "../../tokens/color";
export var StyledImageSelectFlex = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  padding: 10px 5px;\n  align-item: center;\n  gap: 0.5rem;\n  overflow-x: auto;\n\n  ::-webkit-scrollbar {\n    width: 5px;\n  }\n\n  ::-webkit-scrollbar-track {\n    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);\n    border-radius: 15px;\n  }\n\n  ::-webkit-scrollbar-thumb {\n    background-color: ", ";\n    outline: 1px solid ", ";\n    border-radius: 15px;\n  }\n"], ["\n  display: flex;\n  padding: 10px 5px;\n  align-item: center;\n  gap: 0.5rem;\n  overflow-x: auto;\n\n  ::-webkit-scrollbar {\n    width: 5px;\n  }\n\n  ::-webkit-scrollbar-track {\n    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);\n    border-radius: 15px;\n  }\n\n  ::-webkit-scrollbar-thumb {\n    background-color: ", ";\n    outline: 1px solid ", ";\n    border-radius: 15px;\n  }\n"])), PALETTE.primary, PALETTE.grey);
export var StyledSmallImages = styled.img(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  width: 70px;\n  height: 70px;\n  border-radius: 5px;\n  object-fit: cover;\n  outline: ", ";\n  outline-offset: 1.5px;\n  cursor: pointer;\n"], ["\n  width: 70px;\n  height: 70px;\n  border-radius: 5px;\n  object-fit: cover;\n  outline: ", ";\n  outline-offset: 1.5px;\n  cursor: pointer;\n"])), function (props) {
    return props.selected ? "2px solid ".concat(PALETTE.primary) : "none";
});
export var StyledSelectedImage = styled.img(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  width: 100%;\n  height: ", ";\n  border-radius: 10px;\n  object-fit: cover;\n"], ["\n  width: 100%;\n  height: ", ";\n  border-radius: 10px;\n  object-fit: cover;\n"])), function (props) { return (props.height ? props.height : "100%"); });
export var StyledSelectedImageContainer = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  position: relative;\n  width: 100%;\n  height: 100%;\n  display: flex;\n  align-items: center;\n  overflow: hidden;\n  border-radius: 10px;\n\n  .left {\n    position: absolute;\n    left: 5px;\n    min-width: 20px !important;\n    height: 20px;\n    padding: 0 !important;\n    background: rgba(0, 0, 0, 0.1);\n    border: none;\n    border-radius: 50% !important;\n\n    svg {\n      path {\n        fill: ", ";\n      }\n    }\n  }\n\n  .right {\n    position: absolute;\n    right: 5px;\n    min-width: 20px !important;\n    height: 20px;\n    padding: 0 !important;\n    background: rgba(0, 0, 0, 0.1);\n    border: none;\n    border-radius: 50% !important;\n\n    svg {\n      path {\n        fill: ", ";\n      }\n    }\n  }\n"], ["\n  position: relative;\n  width: 100%;\n  height: 100%;\n  display: flex;\n  align-items: center;\n  overflow: hidden;\n  border-radius: 10px;\n\n  .left {\n    position: absolute;\n    left: 5px;\n    min-width: 20px !important;\n    height: 20px;\n    padding: 0 !important;\n    background: rgba(0, 0, 0, 0.1);\n    border: none;\n    border-radius: 50% !important;\n\n    svg {\n      path {\n        fill: ", ";\n      }\n    }\n  }\n\n  .right {\n    position: absolute;\n    right: 5px;\n    min-width: 20px !important;\n    height: 20px;\n    padding: 0 !important;\n    background: rgba(0, 0, 0, 0.1);\n    border: none;\n    border-radius: 50% !important;\n\n    svg {\n      path {\n        fill: ", ";\n      }\n    }\n  }\n"])), PALETTE.light, PALETTE.light);
export var StyledIndicatorsContainer = styled.div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  width: 100%;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  position: absolute;\n  bottom: 10px;\n  margin: 0 auto;\n"], ["\n  width: 100%;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  position: absolute;\n  bottom: 10px;\n  margin: 0 auto;\n"])));
export var StyledIndicators = styled.div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  width: 10px;\n  height: 10px;\n  background: ", ";\n  border: 1px solid ", ";\n  border-radius: 50%;\n  margin: 0 2.5px;\n  cursor: pointer;\n"], ["\n  width: 10px;\n  height: 10px;\n  background: ", ";\n  border: 1px solid ", ";\n  border-radius: 50%;\n  margin: 0 2.5px;\n  cursor: pointer;\n"])), function (props) {
    return props.selected ? "".concat(PALETTE.light) : "rgba(0, 0, 0, 0.1)";
}, PALETTE.light);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
//# sourceMappingURL=styled.js.map